CREATE TABLE `IPRSN40T` (
	`LANG_CLS`	NUMBER	NOT NULL	COMMENT '01:영어,02:일어,03:독어,04:불어,05:중국어',
	`SEQ_NO`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`TEST_CD`	NUMBER	NULL	COMMENT '1. TOEIC
2. TOEFL
3. TEPS
4. JPT',
	`TEST_DATE`	DATE	NULL,
	`POINT`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN41T` (
	`LANG_CLS`	NUMBER	NOT NULL	COMMENT '1. 영어
2. 일어
3. 독어
4. 불어
5. 중국어',
	`SEQ_NO`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`RW_GRADE`	VARCHAR(255)	NULL,
	`SL_GRADE`	VARCHAR(255)	NULL
);

CREATE TABLE `IDEPT10T` (
	`DEPT_CO`	VARCHAR(255)	NOT NULL	COMMENT '발령T의 부서 :  MAX(st_date<=발령일)&&부서T.부서코드=발령T.부서코드',
	`ST_DATE`	VARCHAR(255)	NULL,
	`ED_DATE`	DATE	NULL,
	`DEPT_NM`	VARCHAR(255)	NULL,
	`PDEPT_CD`	VARCHAR(255)	NULL,
	`INDEPT_CD`	VARCHAR(255)	NULL,
	`COMPANY_CD`	VARCHAR(255)	NULL,
	`DEPT_LVL`	VARCHAR(255)	NULL,
	`DEPT_KIND`	VARCHAR(255)	NULL,
	`CAP_EMP`	VARCHAR(255)	NULL,
	`DEPT_EMAIL`	VARCHAR(255)	NULL,
	`ent_fee_yn`	VARCHAR(255)	NULL,
	`SALE_CLS`	VARCHAR(255)	NOT NULL,
	`BUSINESS_GROUP_CD`	VARCHAR(255)	NOT NULL,
	`ORDER_CD`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `IPRSN60T` (
	`ORDER_DATE`	DATE	NOT NULL,
	`SEQ_NO`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`DEPT_CO`	VARCHAR(255)	NOT NULL	COMMENT '발령T의 부서 :  MAX(st_date<=발령일)&&부서T.부서코드=발령T.부서코드',
	`ORDER_CD`	VARCHAR(255)	NULL,
	`COMPANY_CD`	VARCHAR(255)	NULL,
	`JIKGUB`	VARCHAR(255)	NULL,
	`JIKWI`	VARCHAR(255)	NULL,
	`JIKCHAK`	VARCHAR(255)	NULL,
	`STATUS`	VARCHAR(255)	NULL	DEFAULT A,
	`JIKGUN`	VARCHAR(255)	NULL	DEFAULT MO,
	`JIKWI_YEAR_CNT`	NUMBER	NULL,
	`JIKWI_YEAR_TERM`	VARCHAR(255)	NULL,
	`CREATE_DATE`	DATE	NULL,
	`CREATE_EMP`	VARCHAR(255)	NULL,
	`Gyeomjik`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN30T` (
	`SEQ_NO`	NUMBER	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`CERTI_CD`	VARCHAR(255)	NULL,
	`CERTI_GRD`	VARCHAR(255)	NULL,
	`CERTI_DATE`	DATE	NULL,
	`ORG_NM`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN80T` (
	`SEQ_NO`	NUMBER	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`EDU_COMP_CLS`	VARCHAR(255)	NULL,
	`EDU_ST_DATE`	DATE	NULL,
	`EDU_ED_DATE`	DATE	NULL,
	`EDU_COMP_NM`	VARCHAR(255)	NULL,
	`EDU_CS_NM`	VARCHAR(255)	NULL,
	`EDU_REMARK`	VARCHAR(255)	NULL,
	`EDU_CONFIRMYN`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN20T` (
	`SEQ_NO`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`ACDM_CLS`	VARCHAR(255)	NULL,
	`ENTRNC_DATE`	DATE	NULL,
	`GRDT_DATE`	DATE	NULL,
	`SCHOOL_CD`	VARCHAR(255)	NULL,
	`SCHOOL_NM`	VARCHAR(255)	NULL,
	`LOCATION`	VARCHAR(255)	NULL,
	`DAYTIME_CLS`	VARCHAR(255)	NULL,
	`GET_MARKS`	VARCHAR(255)	NULL,
	`FULL_MARKS`	VARCHAR(255)	NULL,
	`MAJOR_NM`	VARCHAR(255)	NULL,
	`MAJOR_DEGREE`	VARCHAR(255)	NULL,
	`MINOR_NM`	VARCHAR(255)	NULL,
	`MINOR_DEGREE`	VARCHAR(255)	NULL,
	`DEGREE_NO`	VARCHAR(255)	NULL,
	`GRDT_CLS`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN01T` (
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`CHNS_NAME`	VARCHAR(255)	NULL,
	`ENG_NAME`	VARCHAR(255)	NULL,
	`BIRTHDAY`	VARCHAR(255)	NULL,
	`BIRTH_CLS`	VARCHAR(255)	NULL,
	`RELIGION`	VARCHAR(255)	NULL,
	`HOBBY`	VARCHAR(255)	NULL,
	`HTEL_NO`	VARCHAR(255)	NULL,
	`POST_NO`	VARCHAR(255)	NULL,
	`POST_SEQ`	NUMBER	NULL,
	`DETL_ADDR`	VARCHAR(255)	NULL,
	`POST_NO_B`	VARCHAR(255)	NULL,
	`POST_SEQ_B`	NUMBER	NULL,
	`DETL_ADDR_B`	VARCHAR(255)	NULL,
	`HEIGHT`	NUMBER	NULL,
	`WEIGHT`	NUMBER	NULL,
	`SIGHT_L`	NUMBER	NULL,
	`SIGHT_R`	NUMBER	NULL,
	`SIGHT_CLS`	VARCHAR(255)	NULL,
	`BLOOD_ABO`	VARCHAR(255)	NULL,
	`BLOOD_RH`	VARCHAR(255)	NULL,
	`SICK_HISTORY`	VARCHAR(255)	NULL,
	`ARMY_ST_DATE`	VARCHAR(255)	NULL,
	`ARMY_ED_DATE`	VARCHAR(255)	NULL,
	`ARMY_TYPE`	VARCHAR(255)	NULL,
	`ARMY_CLS`	VARCHAR(255)	NULL,
	`ARMY_ARM`	VARCHAR(255)	NULL,
	`ARMY_PCLS`	VARCHAR(255)	NULL,
	`ARMY_ECHELON`	VARCHAR(255)	NULL,
	`ARMY_INCMPLT`	VARCHAR(255)	NULL,
	`ARMY_EXCPT_CLS`	VARCHAR(255)	NULL,
	`MARRY_CLS`	VARCHAR(255)	NULL,
	`MARRY_DATE`	VARCHAR(255)	NULL,
	`EXPLOIT_NO`	VARCHAR(255)	NULL,
	`EXPLOIT_REL`	VARCHAR(255)	NULL,
	`LESION_TYPE`	VARCHAR(255)	NULL,
	`LESION_SERIS`	VARCHAR(255)	NULL,
	`LESION_GRADE`	VARCHAR(255)	NULL,
	`LESION_ID_CLS`	VARCHAR(255)	NULL,
	`LESION_ID_DATE`	VARCHAR(255)	NULL,
	`FOREIGNER_CLS`	VARCHAR(255)	NULL,
	`NOMINATOR`	VARCHAR(255)	NULL,
	`PHOTO_PATH`	VARCHAR(255)	NULL,
	`NATION_CLS`	VARCHAR(255)	NULL,
	`VISA_CLS`	VARCHAR(255)	NULL,
	`ATTACH_NO`	VARCHAR(255)	NULL,
	`INTV_ATTACH_NO`	VARCHAR(255)	NULL,
	`RN_POST_NO_B`	VARCHAR(255)	NULL,
	`RN_ADDR_DETL_B`	VARCHAR(255)	NULL,
	`RN_YN_B`	VARCHAR(255)	NULL,
	`RN_ADDR_B`	VARCHAR(255)	NULL,
	`RN_POST_NO`	VARCHAR(255)	NULL,
	`RN_ADDR_DETL`	VARCHAR(255)	NULL,
	`RN_YN`	VARCHAR(255)	NULL,
	`RN_ADDR`	VARCHAR(255)	NULL,
	`CIRCLE_CD`	VARCHAR(255)	NULL,
	`CIRCLE_NM`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN70T` (
	`SEQ_NO`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`JUSTC_CLS`	VARCHAR(255)	NULL,
	`JUSTC_DATE`	DATE	NULL,
	`JUSTC_KIND`	VARCHAR(255)	NULL,
	`JUSTC_DETL_NM`	VARCHAR(255)	NULL,
	`JUSTC_ORG_NM`	VARCHAR(255)	NULL,
	`JUSTC_CONTENT`	VARCHAR(255)	NULL
);

CREATE TABLE `ORDER_CD` (
	`ORDER_CD`	VARCHAR(255)	NOT NULL,
	`ORDER_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN00T` (
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`RES_NO`	VARCHAR(255)	NULL,
	`COMPANY_CD`	VARCHAR(255)	NULL,
	`DEPT_CD`	VARCHAR(255)	NULL,
	`JIKGUB`	VARCHAR(255)	NULL,
	`JIKWI`	VARCHAR(255)	NULL,
	`JIKCHAK`	VARCHAR(255)	NULL,
	`STATUS`	VARCHAR(255)	NULL,
	`ENTER_DATE`	VARCHAR(255)	NULL,
	`REST_DATE`	VARCHAR(255)	NULL,
	`DD_WORK`	VARCHAR(255)	NULL,
	`TEL_NO`	VARCHAR(255)	NULL,
	`MOBILE_NO`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL,
	`EMP_CLS`	VARCHAR(255)	NULL,
	`WORK_ST_DATE`	VARCHAR(255)	NULL,
	`WORK_ED_DATE`	VARCHAR(255)	NULL,
	`JIKGUN`	VARCHAR(255)	NULL,
	`JIKWI_YEAR_CNT`	NUMBER(2,0)	NULL,
	`JIKWI_YEAR_TERM`	VARCHAR(255)	NULL,
	`AGENCY_CLS`	VARCHAR(255)	NULL,
	`GROUP_DATE`	VARCHAR(255)	NULL,
	`RECRUIT_REQ_NO`	VARCHAR(255)	NULL,
	`RECRUIT_TEQ_SEQ`	NUMBER(3)	NULL,
	`RCP_NO`	VARCHAR(255)	NULL
);

CREATE TABLE `SALE_CLS` (
	`SALE_CLS`	VARCHAR(255)	NOT NULL,
	`SALE_CLS_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `BUSINESS_GROUP_CD` (
	`BUSINESS_GROUP_CD`	VARCHAR(255)	NOT NULL,
	`BUSINESS_GROUP_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `IDEPT00T` (
	`DEPT_CO`	VARCHAR(255)	NOT NULL,
	`DEPT_NM`	VARCHAR(255)	NULL,
	`PDEPT_CD`	VARCHAR(255)	NULL,
	`INDEPT_CD`	VARCHAR(255)	NULL,
	`COMPANY_CD`	VARCHAR(255)	NULL,
	`DEPT_LVL`	VARCHAR(255)	NULL,
	`DEPT_KIND`	VARCHAR(255)	NULL,
	`CAP_EMP`	VARCHAR(255)	NULL,
	`ED_DATE`	VARCHAR(255)	NULL,
	`SALE_CLS`	VARCHAR(255)	NULL,
	`DEPT_EMAIL`	VARCHAR(255)	NULL,
	`BUSINESS_GROUP_CD`	VARCHAR(255)	NULL,
	`ent_fee_yn`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN50T` (
	`SEQ_NO`	NUMBER	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`FAMILY_CLS`	VARCHAR(255)	NULL,
	`FAMILY_NAME`	VARCHAR(255)	NULL,
	`FAMILY_RES_NO`	VARCHAR(255)	NULL,
	`FAMILY_LIVE_CLS`	VARCHAR(255)	NULL,
	`FAMILY_SUPPORT_CLS`	VARCHAR(255)	NULL,
	`FAMILY_TAX_SUPPORT_CD`	VARCHAR(255)	NULL,
	`FAMILY_WORK_CLS`	VARCHAR(255)	NULL,
	`FAMILY_FOREIGNER_CLS`	VARCHAR(255)	NULL,
	`FAMILY_TAX_RELIEF_SLC`	VARCHAR(255)	NULL,
	`FAMILY_LESSION_CLS`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN10T` (
	`CAREER_ST_DATE`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`CARRER_ED_DATE`	VARCHAR(255)	NULL,
	`CAREER_COMPANY_NM`	VARCHAR(255)	NULL,
	`CAREER_DEPT_NM`	VARCHAR(255)	NULL,
	`CARRER_JIKWI_NM`	VARCHAR(255)	NULL,
	`CARRER_JIKCHAK_NM`	VARCHAR(255)	NULL,
	`CARRER_ETC_CONT`	VARCHAR(255)	NULL
);

CREATE TABLE `IPRSN61T` (
	`DEPT_CD`	VARCHAR(255)	NOT NULL,
	`EMP_NO`	VARCHAR(255)	NOT NULL,
	`ORDER_DATE`	VARCHAR(255)	NULL,
	`JIKWI`	VARCHAR(255)	NULL,
	`JIKCHAK`	VARCHAR(255)	NULL,
	`CREATE_EMP`	VARCHAR(255)	NULL,
	`CREATE_DATE`	VARCHAR(255)	NULL
);

CREATE TABLE `IATTD10T` (
	`DOC_NO`	VARCHAR(20)	NOT NULL,
	`ATTD_KIND`	VARCHAR(4)	NULL,
	`EMP_NO`	VARCHAR(7)	NULL,
	`INPUT_DATE`	VARCHAR(8)	NULL,
	`ST_DATE`	VARCHAR(8)	NULL,
	`ED_DATE`	VARCHAR(8)	NULL,
	`OUT_TIME`	VARCHAR(4)	NULL,
	`CONTENT`	VARCHAR(750)	NULL,
	`STATUS`	VARCHAR(1)	NULL,
	`APPR_NO`	VARCHAR(20)	NULL,
	`WRITE_EMP`	VARCHAR(7)	NULL,
	`AGENCY_WORK`	VARCHAR(2000)	NULL,
	`DOC_SEQ`	VARCHAR(20)	NULL,
	`ATTACH_NO`	VARCHAR(20)	NULL
);

ALTER TABLE `IPRSN40T` ADD CONSTRAINT `PK_IPRSN40T` PRIMARY KEY (
	`LANG_CLS`,
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN41T` ADD CONSTRAINT `PK_IPRSN41T` PRIMARY KEY (
	`LANG_CLS`,
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IDEPT10T` ADD CONSTRAINT `PK_IDEPT10T` PRIMARY KEY (
	`DEPT_CO`
);

ALTER TABLE `IPRSN60T` ADD CONSTRAINT `PK_IPRSN60T` PRIMARY KEY (
	`ORDER_DATE`,
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN30T` ADD CONSTRAINT `PK_IPRSN30T` PRIMARY KEY (
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN80T` ADD CONSTRAINT `PK_IPRSN80T` PRIMARY KEY (
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN20T` ADD CONSTRAINT `PK_IPRSN20T` PRIMARY KEY (
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN01T` ADD CONSTRAINT `PK_IPRSN01T` PRIMARY KEY (
	`EMP_NO`
);

ALTER TABLE `IPRSN70T` ADD CONSTRAINT `PK_IPRSN70T` PRIMARY KEY (
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `ORDER_CD` ADD CONSTRAINT `PK_ORDER_CD` PRIMARY KEY (
	`ORDER_CD`
);

ALTER TABLE `IPRSN00T` ADD CONSTRAINT `PK_IPRSN00T` PRIMARY KEY (
	`EMP_NO`
);

ALTER TABLE `SALE_CLS` ADD CONSTRAINT `PK_SALE_CLS` PRIMARY KEY (
	`SALE_CLS`
);

ALTER TABLE `BUSINESS_GROUP_CD` ADD CONSTRAINT `PK_BUSINESS_GROUP_CD` PRIMARY KEY (
	`BUSINESS_GROUP_CD`
);

ALTER TABLE `IDEPT00T` ADD CONSTRAINT `PK_IDEPT00T` PRIMARY KEY (
	`DEPT_CO`
);

ALTER TABLE `IPRSN50T` ADD CONSTRAINT `PK_IPRSN50T` PRIMARY KEY (
	`SEQ_NO`,
	`EMP_NO`
);

ALTER TABLE `IPRSN10T` ADD CONSTRAINT `PK_IPRSN10T` PRIMARY KEY (
	`CAREER_ST_DATE`,
	`EMP_NO`
);

ALTER TABLE `IPRSN61T` ADD CONSTRAINT `PK_IPRSN61T` PRIMARY KEY (
	`DEPT_CD`,
	`EMP_NO`
);

ALTER TABLE `IATTD10T` ADD CONSTRAINT `PK_IATTD10T` PRIMARY KEY (
	`DOC_NO`
);

ALTER TABLE `IPRSN40T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN40T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN41T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN41T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN60T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN60T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN30T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN30T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN80T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN80T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN20T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN20T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN01T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN01T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN70T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN70T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN50T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN50T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN10T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN10T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

ALTER TABLE `IPRSN61T` ADD CONSTRAINT `FK_IPRSN00T_TO_IPRSN61T_1` FOREIGN KEY (
	`EMP_NO`
)
REFERENCES `IPRSN00T` (
	`EMP_NO`
);

