CREATE TABLE "INDUSTRY" (
	"INDUSTRY_CODE"	VARCHAR(255)		NOT NULL,
	"INDUSTRY_SECTOR"	VARCHAR(255)		NULL,
	"INDUSTRY_REMARKS"	VARCHAR(255)		NULL,
	"INDUSTRY_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "TAXOFFICE" (
	"TAXOFFICE_CODE"	VARCHAR(255)		NOT NULL,
	"TAXOFFICE_NAME"	VARCHAR(255)		NULL,
	"TAXOFFICE_AFFILIATION"	VARCHAR(255)		NULL
);

CREATE TABLE "COMPANY" (
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_REG_NUM"	VARCHAR(255)		NULL,
	"COMPANY_COR_REG_NUM"	VARCHAR(255)		NULL,
	"COMPANY_CEO_NAME"	VARCHAR(255)		NULL,
	"COMPANY_IS_FOREIGNER"	VARCHAR(255)		NULL,
	"COMPANY_CEO_ID_NUM"	VARCHAR(255)		NULL,
	"COMPANY_TEL"	VARCHAR(255)		NULL,
	"COMPANY_ITEM"	VARCHAR(255)		NULL,
	"INDUSTRY_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_FOUNDATION_DATE"	DATE		NULL,
	"COMPANY_OPEN_DATE"	DATE		NULL,
	"COMPANY_CLOSE_DATE"	DATE		NULL,
	"COMPANY_NAME"	VARCHAR(255)		NULL,
	"COMPANY_TYPE"	VARCHAR(255)		NULL,
	"COMPANY_IS_USE"	VARCHAR(255)		NULL,
	"COMPANY_FISCAL_PERIOD"	VARCHAR(255)		NULL,
	"COMPANY_FISCAL_START_DATE"	DATE		NULL,
	"COMPANY_FISCAL_END_DATE"	DATE		NULL,
	"COMPANY_FAX"	VARCHAR(255)		NULL,
	"COMPANY_BIZ_CONDITION"	VARCHAR(255)		NULL,
	"COMPANY_IS_HEAD"	VARCHAR(255)		NULL,
	"COMPANY_IS_PAY_ALL"	VARCHAR(255)		NULL,
	"COMPANY_OHEAD_CODE"	VARCHAR(255)		NULL,
	"COMPANY_CORPERATION_TYPE"	VARCHAR(255)		NULL,
	"TAXOFFICE_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_CORP_TYPE_CODE"	VARCHAR(255)		NOT NULL,
	"TAXREFUNDBANK_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_IS_SMALL_BUSINESSES"	VARCHAR(255)		NULL,
	"COMPANY_EXTRA_TYPE"	VARCHAR(255)		NULL,
	"COMPANY_PERSON_IN_CHARGE_DEPARTMENT"	VARCHAR(255)		NULL,
	"COMPANY_PERSON_IN_CHARGE_NAME"	VARCHAR(255)		NULL,
	"COMPANY_PERSON_IN_CHARGE_EMAIL"	VARCHAR(255)		NULL,
	"COMPANY_ADDRESS_NUM"	VARCHAR(255)		NULL,
	"COMPANY_ADDRESS_FULL"	VARCHAR(255)		NULL,
	"COMPANY_TAXATION_TYPE"	VARCHAR(255)		NULL,
	"COMPANY_RESIDENCE"	VARCHAR(255)		NULL,
	"COMPANY_CEO_CLASSIFICATION"	VARCHAR(255)		NULL,
	"COMPANY_PARTNERSHIP"	VARCHAR(255)		NULL,
	"COMPANY_CEO_ADDRESS_NUM"	VARCHAR(255)		NULL,
	"COMPANY_CEO_ADDRESS_FULL"	VARCHAR(255)		NULL,
	"COMPANY_CEO_TEL"	VARCHAR(255)		NULL,
	"LOCALTAX_CEO_CODE"	VARCHAR(255)		NOT NULL,
	"TAXOFFICE_CEO_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_CEO_DONG_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_INCOME_CODE"	VARCHAR(255)		NULL,
	"COMPANY_INCOME_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "EMPLOYEE" (
	"EMPLOYEE_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL,
	"EMPLOYEE_NAME"	VARCHAR(255)		NULL,
	"EMPLOYEE_POSITION"	VARCHAR(255)		NULL,
	"EMPLOYEE_RANK"	VARCHAR(255)		NULL,
	"EMPLOYEE_JOB"	VARCHAR(255)		NULL,
	"EMPLOYEE_VALUE"	VARCHAR(255)		NULL,
	"EMPLOYEE_ID"	VARCHAR(255)		NULL,
	"EMPLOYEE_PASSWORD"	VARCHAR(255)		NULL,
	"EMPLOYEE_EMAIL"	VARCHAR(255)		NULL,
	"EMPLOYEE_PHONE"	VARCHAR(255)		NULL,
	"EMPLOYEE_SKILL"	VARCHAR(255)		NULL,
	"DEPARTMENT_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "LOCALTAX" (
	"LOCALTAX_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "DOC" (
	"DOC_ROWSEQ"	NUMBER		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL,
	"DOC_DATE"	DATE		NULL,
	"DOC_ORDER"	VARCHAR(255)		NULL,
	"DOC_MOVEDCOPIED"	VARCHAR(255)		NULL,
	"DOC_PARENT"	VARCHAR(255)		NULL,
	"EMPLOYEE_CODE"	VARCHAR(255)		NULL,
	"SITE_CODE"	VARCHAR(255)		NULL,
	"PROJECT_CODE"	VARCHAR(255)		NULL,
	"DOCTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCTYPE" (
	"DOCTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"DOCTYPE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "ADMINITEM" (
	"ADMINITEM_CODE"	VARCHAR(255)		NOT NULL,
	"ADMINITEM_NAME"	VARCHAR(255)		NULL,
	"ADMINITEM_CONTENT"	VARCHAR(255)		NULL
);

CREATE TABLE "ACCOUNT" (
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"STDACCOUNT_CODE"	VARCHAR(255)		NULL,
	"ACCOUNT_4NAME"	VARCHAR(255)		NULL,
	"ACCOUNT_USAGE"	VARCHAR(255)		NULL,
	"ACCOUNT_REL"	VARCHAR(255)		NULL,
	"ACCOUNT_PRNAME"	VARCHAR(255)		NULL,
	"ACCOUNT_ENG"	VARCHAR(255)		NULL,
	"ACCOUNT_3NAME"	VARCHAR(255)		NULL,
	"ACCOUNT_2NAME"	VARCHAR(255)		NULL,
	"ACCOUNT_1NAME"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL,
	"ACCOUNT_DEBIT"	VARCHAR(255)		NULL,
	"ACCOUNT_PARENT"	VARCHAR(255)		NULL,
	"ACCOUNT_ADMIN"	VARCHAR(255)		NULL,
	"ACCOUNT_TYPE"	VARCHAR(255)		NULL
);

CREATE TABLE "SITE" (
	"SITE_CODE"	VARCHAR(255)		NOT NULL,
	"SITE_NAME"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCPRODUCT" (
	"DOCPRODUCT_ROWSEQ"	NUMBER		NOT NULL,
	"DOC_ROWSEQ"	NUMBER		NOT NULL,
	"DOCPRODUCT_NAME"	VARCHAR(255)		NULL,
	"DOCPRODUCT_QUANTITY"	NUMBER		NULL,
	"DOCPRODUCT_UNITPRICE"	NUMBER		NULL,
	"DOCPRODUCT_PRICE"	NUMBER		NULL,
	"DOCPRODUCT_VAT"	NUMBER		NULL,
	"DOCPRODUCT_REMARK"	VARCHAR(255)		NULL,
	"PRODUCT_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "PRODUCT" (
	"PRODUCT_CODE"	VARCHAR(255)		NOT NULL,
	"PRODUCT_NAME"	VARCHAR(255)		NULL,
	"PRODUCT_TYPE"	VARCHAR(255)		NULL,
	"PRODUCT_TAXTYPE"	VARCHAR(255)		NULL,
	"PRODUCT_REMARKS"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "LOCALTAX_CORP_TYPE" (
	"LOCALTAX_CORP_TYPE_CODE"	VARCHAR(255)		NOT NULL,
	"LOCALTAX_CORP_TYPE_CORPERATION"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCSALES" (
	"DOC_ROWSEQ"	NUMBER		NOT NULL,
	"DOCSALES_PRODUCTNAME"	VARCHAR(255)		NULL,
	"DOCSALES_TOTALPRICE"	NUMBER		NULL,
	"DOCSALES_TOTALVAT"	NUMBER		NULL,
	"DOCSALES_TOTALAMOUNT"	NUMBER		NULL,
	"DOCSALES_ELECTAX"	VARCHAR(255)		NULL,
	"DOCSALES_CLIENT"	VARCHAR(255)		NULL,
	"CLIENT_CODE"	VARCHAR(255)		NULL,
	"DOCSALESTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"VATNONDEDUCTIBLE_CODE"	VARCHAR(255)		NULL,
	"DOCSALESJOURNAL_CODE"	NUMBER		NOT NULL,
	"DOCTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENT_OCARD_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET" (
	"FIXEDASSET_CODE"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"EMPLOYEE_CODE"	VARCHAR(255)		NULL,
	"SITE_CODE"	VARCHAR(255)		NULL,
	"INDUSTRY_CODE"	VARCHAR(255)		NULL,
	"PROJECT_CODE"	VARCHAR(255)		NULL,
	"FIXEDASSET_NAME"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_DATE"	DATE		NULL,
	"FIXEDASSET_AMOUNTSET"	NUMBER		NULL,
	"FIXEDASSET_PRECUTSUM"	NUMBER		NULL,
	"FIXEDASSET_PRESET"	NUMBER		NULL,
	"FIXEDASSET_NEWPLUS"	NUMBER		NULL,
	"FIXEDASSET_PARTSELLDISUSE"	NUMBER		NULL,
	"FIXEDASSET_TRUSTAMOUNTSET"	NUMBER		NULL,
	"FIXEDASSET_TRUSTCUTSUM"	NUMBER		NULL,
	"FIXEDASSET_TRUSTCUTSET"	NUMBER		NULL,
	"FIXEDASSET_CUTSET"	NUMBER		NULL,
	"FIXEDASSET_CUTTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_DURATIONRATIO"	NUMBER		NULL,
	"FIXEDASSET_DURATIONTIME"	NUMBER		NULL,
	"FIXEDASSET_ISCUTFINISHDATE"	DATE		NULL,
	"FIXEDASSET_CUTAMOUNT"	NUMBER		NULL,
	"FIXEDASSET_TRUSTBOOKAMOUNT"	NUMBER		NULL,
	"FIXEDASSET_PREOVERCUTSUM"	NUMBER		NULL,
	"FIXEDASSET_PREPAYSUM"	NUMBER		NULL,
	"FIXEDASSET_CUTNOW"	NUMBER		NULL,
	"FIXEDASSET_CUTASSUMESUM"	NUMBER		NULL,
	"FIXEDASSET_CUTRANGE"	NUMBER		NULL,
	"FIXEDASSET_CUTRATIO"	NUMBER		NULL,
	"FIXEDASSET_SPECIALCUTRATIO"	NUMBER		NULL,
	"FIXEDASSET_SPECIALCUTAMOUNT"	NUMBER		NULL,
	"FIXEDASSET_CUTSUM"	NUMBER		NULL,
	"FIXEDASSET_SET"	NUMBER		NULL,
	"FIXEDASSET_ISSPECIAL_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_ISCAR_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_AMOUNT"	NUMBER		NULL,
	"FIXEDASSET_TYPERANGE_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_GIVEDATE"	DATE		NULL,
	"FIXEDASSET_MINOVERCUTSET"	NUMBER		NULL,
	"FIXEDASSET_CUTASSUMEAMOUNT"	NUMBER		NULL,
	"FIXEDASSET_DISUSEDATE"	DATE		NULL,
	"FIXEDASSET_MANAGECODE"	VARCHAR(255)		NULL,
	"FIXEDASSET_GETBY"	VARCHAR(255)		NULL,
	"FIXEDASSET_MADEBY"	VARCHAR(255)		NULL,
	"FIXEDASSET_SIZE"	VARCHAR(255)		NULL,
	"FIXEDASSET_MODEL"	VARCHAR(255)		NULL,
	"FIXEDASSET_REMARKS"	VARCHAR(255)		NULL,
	"FIXEDASSET_HISTORY"	NUMBER		NULL,
	"FIXEDASSET_TYPE_CODE"	VARCHAR(255)		NOT NULL,
	"EMPLOYEE_MANAGE_CODE"	VARCHAR(255)		NULL,
	"EMPLOYEE_USE_CODE"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "CLIENTTYPE" (
	"CLIENTTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENTTYPE_NAME"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "CLIENT" (
	"CLIENT_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENT_NAME"	VARCHAR(255)		NULL,
	"CLIENT_NUMBER"	VARCHAR(255)		NULL,
	"CLIENT_REPRESENTATION"	VARCHAR(255)		NULL,
	"CLIENT_DIVISION"	VARCHAR(255)		NULL,
	"CLIENT_IS_USE"	VARCHAR(255)		NULL,
	"CLIENT_BUSINESS_CONDITION"	VARCHAR(255)		NULL,
	"CLIENT_EVENT"	VARCHAR(255)		NULL,
	"CLIENT_ZIPCODE"	VARCHAR(255)		NULL,
	"CLIENT_ADDRESS"	VARCHAR(255)		NULL,
	"CLIENT_TEL"	VARCHAR(255)		NULL,
	"CLIENT_FAX"	VARCHAR(255)		NULL,
	"CLIENT_IS_MAIN_ESTABLISHMENT"	VARCHAR(255)		NULL,
	"CLIENT_UNIT_REPORT_CLIENT"	VARCHAR(255)		NULL,
	"CLIENT_OUTPUT_NAME"	VARCHAR(255)		NULL,
	"CLIENT_STARTDATE"	DATE		NULL,
	"CLIENT_ENDDATE"	DATE		NULL,
	"CLIENT_NOTE"	VARCHAR(255)		NULL,
	"CLIENT_IN_CHARGE_TEL"	VARCHAR(255)		NULL,
	"CLIENT_IN_CHARGE_EMAIL"	VARCHAR(255)		NULL,
	"CLIENT_HOMEPAGE"	VARCHAR(255)		NULL,
	"CLIENT_BANK_ACCOUNT"	VARCHAR(255)		NULL,
	"CLIENT_ODEPOSIT_ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENT_EXTRA_LIMIT_AMOUNT"	VARCHAR(255)		NULL,
	"CLIENT_MORTGAGE_LIMIT_AMOUNT"	VARCHAR(255)		NULL,
	"CLIENT_UNIT_PRICE_SALES"	VARCHAR(255)		NULL,
	"CLIENT_UNIT_PRICE_PURCHASE"	VARCHAR(255)		NULL,
	"CLIENT_LIQUOR_CODE"	VARCHAR(255)		NULL,
	"CLIENT_DEPOSIT_TYPE"	VARCHAR(255)		NULL,
	"CLIENT_INTEREST_RATE"	VARCHAR(255)		NULL,
	"CLIENT_ OVERDRAFT_LIMIT_AMOUNT"	VARCHAR(255)		NULL,
	"CLIENT_OVERDRAFT_DATE"	DATE		NULL,
	"CLIENT_PAYMENT_DATE"	DATE		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL,
	"EMPLOYEE_CODE"	VARCHAR(255)		NULL,
	"CLIENTTYPE_CODE"	VARCHAR(255)		NULL,
	"ACCOUNT_OBASIC_ACCOUNT_CODE"	VARCHAR(255)		NULL,
	"ACCOUNT_ORELATIVE_ACCOUNT_CODE"	VARCHAR(255)		NULL,
	"LOCALTAX_CODE"	VARCHAR(255)		NULL,
	"BANKCODEHELP_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "BANKCODEHELP" (
	"BANKCODEHELP_CODE"	VARCHAR(255)		NOT NULL,
	"BANKCODEHELP_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "ACC_AMITEM_REL" (
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"ADMINITEM_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCJOURNAL" (
	"DOCJOURNAL_ROWSEQ"	NUMBER		NOT NULL,
	"DOCJOURNAL_DEBIT"	VARCHAR(255)		NULL,
	"DOCJOURNAL_CREDIT"	VARCHAR(255)		NULL,
	"DOCJOURNAL_ABSTRACT"	VARCHAR(255)		NULL,
	"DOC_ROWSEQ"	NUMBER		NOT NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENT_CODE"	VARCHAR(255)		NULL,
	"DOCJOURNALTYPE_CODE"	NUMBER		NOT NULL,
	"ABSTRACT_ID"	VARCHAR(255)		NULL
);

CREATE TABLE "CONALL" (
	"CONALL_CODE"	VARCHAR(255)		NOT NULL,
	"CONALL_VAT_INCLUDED"	NUMBER		NULL,
	"CONALL_PROJECT_CODE_USED"	NUMBER		NULL,
	"CONALL_FUNDS_CODE_USED"	NUMBER		NULL,
	"CONALL_SITE_CODE_USED"	NUMBER		NULL,
	"CONALL_ITEM_CODE_USED"	NUMBER		NULL,
	"DISPLAYDIGITS_CODE1"	VARCHAR(255)		NULL,
	"DISPLAYDIGITS_CODE2"	VARCHAR(255)		NULL,
	"DISPLAYDIGITS_CODE3"	VARCHAR(255)		NULL,
	"DISPLAYDIGITS_CODE4"	VARCHAR(255)		NULL,
	"DISPLAYDIGITS_CODE5"	VARCHAR(255)		NULL,
	"DISPLAYDIGITS_CODE6"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DISPLAYDIGITS" (
	"DISPLAYDIGITS_CODE"	VARCHAR(255)		NOT NULL,
	"DISPLAYDIGITS_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "CONACC" (
	"CONACC_CODE"	VARCHAR(255)		NOT NULL,
	"CONACC_FONT_SIZE"	NUMBER		NULL,
	"ACCOUNT_CODE1"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE2"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE3"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE4"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE5"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE6"	VARCHAR(255)		NULL,
	"LANGUAGE_CODE"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET_HISTORY_REL" (
	"FIXEDASSET_CODE"	VARCHAR(255)		NOT NULL,
	"DOC_ROWSEQ"	NUMBER		NOT NULL
);

CREATE TABLE "LANGUAGE" (
	"LANGUAGE_CODE"	VARCHAR(255)		NOT NULL,
	"LANGUAGE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "PROD_EMP_REL" (
	"PRODUCT_CODE"	VARCHAR(255)		NOT NULL,
	"EMPLOYEE_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "STDACCOUNT" (
	"STDACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"STDACCOUNT_NAME"	VARCHAR(255)		NULL,
	"STDACCOUNT_PARENT"	VARCHAR(255)		NULL,
	"STDACCOUNT_DEDUCTTYPE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCJOURNALTYPE" (
	"DOCJOURNALTYPE_CODE"	NUMBER		NOT NULL,
	"DOCJOURNALTYPE_NAME"	VARCHAR(255)		NULL,
	"DOCJOURNALTYPE_DEBITCREDIT"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCSALESJOURNAL" (
	"DOCSALESJOURNAL_CODE"	NUMBER		NOT NULL,
	"DOCTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"DOCSALESJOURNAL_NAME"	VARCHAR(255)		NULL,
	"DOCSALESJOURNAL_DEBITCREDIT"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "DOCSALESTYPE" (
	"DOCSALESTYPE_CODE"	NUMBER		NOT NULL,
	"DOCSALESTYPE_NAME"	VARCHAR(255)		NULL,
	"DOCSALESTYPE_ISVAT"	VARCHAR(255)		NULL,
	"DOCTYPE_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "PROJECT" (
	"PROJECT_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENT_CODE"	VARCHAR(255)		NOT NULL,
	"PROJECT_NAME"	VARCHAR(255)		NULL,
	"PROJECT_STARTDATE"	DATE		NULL,
	"PROJECT_ENDDATE"	DATE		NULL,
	"PROJECT_VALUE"	NUMBER		NULL,
	"PROJECT_CONDITION"	VARCHAR(255)		NULL,
	"PROJECT_ABSTRACT"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "VATNONDEDUCTIBLE" (
	"VATNONDEDUCTIBLE_CODE"	VARCHAR(255)		NOT NULL,
	"VATNONDEDUCTIBLE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "CLOSINGLIST" (
	"CLOSINGLIST_CODE"	VARCHAR(255)		NOT NULL,
	"CLOSINGLIST_NAME"	VARCHAR(255)		NULL,
	"CLOSINGLIST_PARENT"	VARCHAR(255)		NULL
);

CREATE TABLE "DEPARTMENT" (
	"DEPARTMENT_CODE"	VARCHAR(255)		NOT NULL,
	"DEPARTMENT_NAME"	VARCHAR(255)		NULL,
	"DEPARTMENT_OPARENT_CODE"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "PROJ_EMP_REL" (
	"PROJECT_CODE"	VARCHAR(255)		NOT NULL,
	"EMPLOYEE_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "CLOSINGACCOUNTLIST" (
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"CLOSINGLIST_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "ABSTRACT" (
	"ABSTRACT_ID"	VARCHAR(255)		NOT NULL,
	"ABSTRACT_NAME"	VARCHAR(255)		NULL,
	"ABSTRACT_CODE"	VARCHAR(255)		NULL,
	"ABSTRACT_TYPE"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"ABSTRACT_EXTRA"	VARCHAR(255)		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "TAXREFUNDBANK" (
	"TAXREFUNDBANK_CODE"	VARCHAR(255)		NOT NULL,
	"TAXREFUNDBANK_BANKNAME"	VARCHAR(255)		NULL
);

CREATE TABLE "PREBALANCESHEET" (
	"PREBALANCESHEET_YEAR"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_4NAME"	VARCHAR(255)		NULL,
	"PREBALANCESHEET_DEBIT"	VARCHAR(255)		NOT NULL,
	"PREBALANCESHEET_CREDIT"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL,
	"PREBALANCESHEET_SEQ"	VARCHAR(255)		NULL
);

CREATE TABLE "PREINCOMESTATEMENT" (
	"PREINCOMESTATEMENT_STDATE"	VARCHAR(255)		NULL,
	"PREINCOMESTATEMENT_EDDATE"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"PREINCOMESTATEMENT_AMOUNT"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL,
	"PREINCOMESTATEMENT_SEQ"	VARCHAR(255)		NULL
);

CREATE TABLE "PRECOSTOFGOODS" (
	"PRECOSTOFGOODS_YEAR"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"PRECOSTOFGOODS_AMOUNT"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL,
	"PRECOSTOFGOODS_SEQ"	VARCHAR(255)		NULL
);

CREATE TABLE "PRESOA" (
	"PRESOA_SUBJECT"	VARCHAR(255)		NOT NULL,
	"PRESOA_STDATE"	VARCHAR(255)		NULL,
	"PRESOA_EDDATE"	VARCHAR(255)		NULL,
	"PRESOA_CONFIRMDATE"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"PRESOA_AMOUNT"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "CLIENTCARRYOVER" (
	"KCLIENTCARRYOVER_CODE"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"CLIENTCARRYOVER_AMOUNT"	VARCHAR(255)		NOT NULL,
	"COMPANY_CODE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "CARDTX" (
	"APPROVE_NUM"	VARCHAR(255)		NOT NULL,
	"CARD_NUM"	VARCHAR(255)		NOT NULL,
	"TRANS_DATE"	VARCHAR(255)		NULL,
	"APPROVE_DATE"	VARCHAR(255)		NULL,
	"DEAL_DATE"	VARCHAR(255)		NULL,
	"BUY_DATE"	VARCHAR(255)		NULL,
	"CHARGE_DATE"	VARCHAR(255)		NULL,
	"GUBUN"	VARCHAR(255)		NULL,
	"APPROVE_AMT"	VARCHAR(255)		NULL,
	"TAX"	VARCHAR(255)		NULL,
	"FEE"	VARCHAR(255)		NULL,
	"APPROVE_TOTAL"	VARCHAR(255)		NULL,
	"INSTALLMENT_MONTHS"	VARCHAR(255)		NULL,
	"REMAIN_INSTALLMENT_MONTHS"	VARCHAR(255)		NULL,
	"PAY_DATE"	VARCHAR(255)		NULL,
	"PAY_TOTAL"	VARCHAR(255)		NULL,
	"PAY_AMT"	VARCHAR(255)		NULL,
	"PAY_INTEREST"	VARCHAR(255)		NULL,
	"CURRENCY"	VARCHAR(255)		NULL,
	"BUY_EXCHANGE_RATE"	VARCHAR(255)		NULL,
	"BUY_COLLECTION_NUM"	VARCHAR(255)		NULL,
	"SERVICE_CHARGE"	VARCHAR(255)		NULL,
	"VENDOR_NAME"	VARCHAR(255)		NULL,
	"VENDOR_TAX_NUM"	VARCHAR(255)		NULL,
	"VENDOR_NUM"	VARCHAR(255)		NULL,
	"VENDOR_ADDRESS"	VARCHAR(255)		NULL,
	"VENDOR_ZIP_CODE"	VARCHAR(255)		NULL,
	"VENDOR_TEL"	VARCHAR(255)		NULL,
	"USD_AMT"	VARCHAR(255)		NULL,
	"KRW_AMT"	VARCHAR(255)		NULL,
	"ABROAD_USE"	VARCHAR(255)		NULL,
	"ABROAD_CURRENCY"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "CARDTX"."APPROVE_NUM" IS '카드승인번호 (기본키)';

COMMENT ON COLUMN "CARDTX"."CARD_NUM" IS '(기본키)';

COMMENT ON COLUMN "CARDTX"."TRANS_DATE" IS '거래내역전송일자';

COMMENT ON COLUMN "CARDTX"."APPROVE_DATE" IS '거래내역승인일자';

COMMENT ON COLUMN "CARDTX"."DEAL_DATE" IS '카드거래일자';

COMMENT ON COLUMN "CARDTX"."BUY_DATE" IS '카드거래매입일자';

COMMENT ON COLUMN "CARDTX"."CHARGE_DATE" IS '카드거래청구일자';

COMMENT ON COLUMN "CARDTX"."GUBUN" IS '구분코드로변경';

COMMENT ON COLUMN "CARDTX"."APPROVE_AMT" IS '카드거래승인금액';

COMMENT ON COLUMN "CARDTX"."TAX" IS '카드거래세금';

COMMENT ON COLUMN "CARDTX"."FEE" IS '카드거래수수료';

COMMENT ON COLUMN "CARDTX"."APPROVE_TOTAL" IS '카드승인합계';

COMMENT ON COLUMN "CARDTX"."INSTALLMENT_MONTHS" IS '카드거래할부개월수';

COMMENT ON COLUMN "CARDTX"."REMAIN_INSTALLMENT_MONTHS" IS '카드거래잔여할부개월수';

COMMENT ON COLUMN "CARDTX"."PAY_DATE" IS '카드결제일자';

COMMENT ON COLUMN "CARDTX"."PAY_TOTAL" IS '카드결제총금액';

COMMENT ON COLUMN "CARDTX"."PAY_AMT" IS '카드결제원금';

COMMENT ON COLUMN "CARDTX"."PAY_INTEREST" IS '카드결제이자';

COMMENT ON COLUMN "CARDTX"."CURRENCY" IS '카드거래통화코드';

COMMENT ON COLUMN "CARDTX"."BUY_EXCHANGE_RATE" IS '카드거래적용환율';

COMMENT ON COLUMN "CARDTX"."BUY_COLLECTION_NUM" IS '카드매입추심번호';

COMMENT ON COLUMN "CARDTX"."SERVICE_CHARGE" IS '카드거래봉사료';

COMMENT ON COLUMN "CARDTX"."VENDOR_NAME" IS '가맹점명';

COMMENT ON COLUMN "CARDTX"."VENDOR_TAX_NUM" IS '가맹점 사업자번호';

COMMENT ON COLUMN "CARDTX"."VENDOR_NUM" IS '가맹점코드번호';

COMMENT ON COLUMN "CARDTX"."VENDOR_ADDRESS" IS '가맹점주소';

COMMENT ON COLUMN "CARDTX"."VENDOR_ZIP_CODE" IS '가맹점 우편번호';

COMMENT ON COLUMN "CARDTX"."VENDOR_TEL" IS '가맹점 전화번호';

COMMENT ON COLUMN "CARDTX"."USD_AMT" IS '달러환산금액';

COMMENT ON COLUMN "CARDTX"."KRW_AMT" IS '원화환산금액';

COMMENT ON COLUMN "CARDTX"."ABROAD_USE" IS '해외사용여부';

COMMENT ON COLUMN "CARDTX"."ABROAD_CURRENCY" IS '해외사용통화코드';

CREATE TABLE "CARDINFO" (
	"CARD_NUM"	VARCHAR(255)		NOT NULL,
	"USERID"	VARCHAR(255)		NULL,
	"MANAGEDIVNAME"	VARCHAR(255)		NULL,
	"MEMBERKRNAME"	VARCHAR(255)		NULL,
	"MEMBEREGNAME"	VARCHAR(255)		NULL,
	"CORPORATENAME"	VARCHAR(255)		NULL,
	"CARDEXPIREDDATE"	VARCHAR(255)		NULL,
	"ACCOUNTBANK"	VARCHAR(255)		NULL,
	"ACCOUNTNUMBER"	VARCHAR(255)		NULL,
	"ACCOUNTDATE"	VARCHAR(255)		NULL,
	"CARDGUBUN"	VARCHAR(255)		NULL,
	"CARDKINDCODE"	VARCHAR(255)		NULL,
	"JOBCODE"	VARCHAR(255)		NULL,
	"MEMSOCIALNO"	VARCHAR(255)		NULL,
	"CANCELDATE"	VARCHAR(255)		NULL,
	"MEMBERSHIP_FEE"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "CARDINFO"."CARD_NUM" IS '(기본키)';

COMMENT ON COLUMN "CARDINFO"."USERID" IS '사원코드로변경';

COMMENT ON COLUMN "CARDINFO"."MANAGEDIVNAME" IS '조직코드로변경';

COMMENT ON COLUMN "CARDINFO"."MEMBERKRNAME" IS '카드회원명';

COMMENT ON COLUMN "CARDINFO"."MEMBEREGNAME" IS '카드회원명';

COMMENT ON COLUMN "CARDINFO"."CORPORATENAME" IS '카드업체명';

COMMENT ON COLUMN "CARDINFO"."CARDEXPIREDDATE" IS '카드유효기간';

COMMENT ON COLUMN "CARDINFO"."ACCOUNTBANK" IS '은행코드로변경';

COMMENT ON COLUMN "CARDINFO"."ACCOUNTNUMBER" IS '카드결제계좌번호';

COMMENT ON COLUMN "CARDINFO"."ACCOUNTDATE" IS '카드결제출금일자';

COMMENT ON COLUMN "CARDINFO"."CARDGUBUN" IS '카드종류코드로변경';

COMMENT ON COLUMN "CARDINFO"."CARDKINDCODE" IS '법인/개인/등등';

COMMENT ON COLUMN "CARDINFO"."JOBCODE" IS '관련업무코드';

COMMENT ON COLUMN "CARDINFO"."MEMSOCIALNO" IS '카드소속회사사업자번호';

COMMENT ON COLUMN "CARDINFO"."CANCELDATE" IS '카드해지/취소일자';

COMMENT ON COLUMN "CARDINFO"."MEMBERSHIP_FEE" IS '카드연회비';

CREATE TABLE "EXPENDITURE" (
	"EXPENDITURE_NUM"	VARCHAR(255)		NOT NULL,
	"APPROVE_NUM"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_TAX_CODE"	VARCHAR(255)		NULL,
	"DATE"	VARCHAR(255)		NULL,
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"PROJECT_CODE"	VARCHAR(255)		NULL,
	"CLIENT_CODE"	VARCHAR(255)		NULL,
	"REQUEST_PROHIBITION"	VARCHAR(255)		NULL,
	"INVENTORY_CODE"	VARCHAR(255)		NULL,
	"VENDOR_NAME"	VARCHAR(255)		NULL,
	"VENDOR_TAX_NUM"	VARCHAR(255)		NULL,
	"PAYMENT_METHOD"	VARCHAR(255)		NULL,
	"VOUCHER_CODE"	VARCHAR(255)		NOT NULL,
	"USERID"	VARCHAR(255)		NULL,
	"CORPORATE_CARD_NUM"	VARCHAR(255)		NULL,
	"APPROVE_TOTAL"	VARCHAR(255)		NULL,
	"APPROVE_AMT"	VARCHAR(255)		NULL,
	"TAX"	VARCHAR(255)		NULL,
	"APPROVE_DATE"	VARCHAR(255)		NULL,
	"DETAIL"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "EXPENDITURE"."EXPENDITURE_NUM" IS '경비청구번호(일단위, 0부터 시작) (기본키)';

COMMENT ON COLUMN "EXPENDITURE"."APPROVE_NUM" IS '카드승인번호 (기본키)';

CREATE TABLE "EXPENDITURE_ACCOUNT" (
	"ACCOUNT_CODE"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_4NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "VOUCHER" (
	"VOUCHER_CODE"	VARCHAR(255)		NOT NULL,
	"VOUCHER_TYPE"	VARCHAR(255)		NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "VOUCHER"."VOUCHER_TYPE" IS '카드전표/세금계산서(카과)/현금영수증/기타';

CREATE TABLE "LOCKCOMPANY" (
	"LOCKCOMPANY_TYPE"	VARCHAR(255)		NOT NULL
);

CREATE TABLE "FIXEDASSET_ISCAR" (
	"FIXEDASSET_ISCAR_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_ISCAR_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET_ISSPECIAL" (
	"FIXEDASSET_ISSPECIAL_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_ISSPECIAL_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET_TYPE" (
	"FIXEDASSET_TYPE_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_TYPE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET_CUTTYPE" (
	"FIXEDASSET_CUTTYPE_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_CUTTYPE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "FIXEDASSET_TYPERANGE" (
	"FIXEDASSET_TYPERANGE_CODE"	VARCHAR(255)		NOT NULL,
	"FIXEDASSET_TYPERANGE_NAME"	VARCHAR(255)		NULL
);

CREATE TABLE "ACCOUNTTYPE" (
	"ACCOUNT_TYPE"	VARCHAR(255)		NOT NULL,
	"ACCOUNT_TYPENAME"	VARCHAR(255)		NULL
);

CREATE TABLE "CLOSINGPREEXP" (
	"DOC_ROWSEQ"	NUMBER		NOT NULL,
	"CLOSINGPREEXP_NAME"	VARCHAR(255)		NULL,
	"CLOSINGPREEXP_STARTDATE"	DATE		NULL,
	"CLOSINGPREEXP_ENDDATE"	DATE		NULL,
	"CLOSINGPREEXP_BALANCE"	NUMBER		NULL,
	"CLOSINGPREEXP_UPLOADDATE"	DATE		NULL,
	"CLOSINGPREEXP_EXPSUM"	NUMBER		NULL,
	"COMPANY_CODE"	VARCHAR(255)		NULL
);

CREATE TABLE "TRANSACTION" (
	"CODE"	VARCHAR(255)		NOT NULL,
	"MODULE"	VARCHAR(255)		NOT NULL,
	"DATE"	VARCHAR(255)		NULL,
	"Field2"	VARCHAR(255)		NULL,
	"Field3"	VARCHAR(255)		NULL
);

ALTER TABLE "INDUSTRY" ADD CONSTRAINT "PK_INDUSTRY" PRIMARY KEY (
	"INDUSTRY_CODE"
);

ALTER TABLE "TAXOFFICE" ADD CONSTRAINT "PK_TAXOFFICE" PRIMARY KEY (
	"TAXOFFICE_CODE"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"COMPANY_CODE"
);

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY (
	"EMPLOYEE_CODE"
);

ALTER TABLE "LOCALTAX" ADD CONSTRAINT "PK_LOCALTAX" PRIMARY KEY (
	"LOCALTAX_CODE"
);

ALTER TABLE "DOC" ADD CONSTRAINT "PK_DOC" PRIMARY KEY (
	"DOC_ROWSEQ"
);

ALTER TABLE "DOCTYPE" ADD CONSTRAINT "PK_DOCTYPE" PRIMARY KEY (
	"DOCTYPE_CODE"
);

ALTER TABLE "ADMINITEM" ADD CONSTRAINT "PK_ADMINITEM" PRIMARY KEY (
	"ADMINITEM_CODE"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
	"ACCOUNT_CODE"
);

ALTER TABLE "SITE" ADD CONSTRAINT "PK_SITE" PRIMARY KEY (
	"SITE_CODE"
);

ALTER TABLE "DOCPRODUCT" ADD CONSTRAINT "PK_DOCPRODUCT" PRIMARY KEY (
	"DOCPRODUCT_ROWSEQ",
	"DOC_ROWSEQ"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_CODE"
);

ALTER TABLE "LOCALTAX_CORP_TYPE" ADD CONSTRAINT "PK_LOCALTAX_CORP_TYPE" PRIMARY KEY (
	"LOCALTAX_CORP_TYPE_CODE"
);

ALTER TABLE "DOCSALES" ADD CONSTRAINT "PK_DOCSALES" PRIMARY KEY (
	"DOC_ROWSEQ"
);

ALTER TABLE "FIXEDASSET" ADD CONSTRAINT "PK_FIXEDASSET" PRIMARY KEY (
	"FIXEDASSET_CODE"
);

ALTER TABLE "CLIENTTYPE" ADD CONSTRAINT "PK_CLIENTTYPE" PRIMARY KEY (
	"CLIENTTYPE_CODE"
);

ALTER TABLE "CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY (
	"CLIENT_CODE"
);

ALTER TABLE "BANKCODEHELP" ADD CONSTRAINT "PK_BANKCODEHELP" PRIMARY KEY (
	"BANKCODEHELP_CODE"
);

ALTER TABLE "ACC_AMITEM_REL" ADD CONSTRAINT "PK_ACC_AMITEM_REL" PRIMARY KEY (
	"ACCOUNT_CODE",
	"ADMINITEM_CODE"
);

ALTER TABLE "DOCJOURNAL" ADD CONSTRAINT "PK_DOCJOURNAL" PRIMARY KEY (
	"DOCJOURNAL_ROWSEQ"
);

ALTER TABLE "CONALL" ADD CONSTRAINT "PK_CONALL" PRIMARY KEY (
	"CONALL_CODE"
);

ALTER TABLE "DISPLAYDIGITS" ADD CONSTRAINT "PK_DISPLAYDIGITS" PRIMARY KEY (
	"DISPLAYDIGITS_CODE"
);

ALTER TABLE "CONACC" ADD CONSTRAINT "PK_CONACC" PRIMARY KEY (
	"CONACC_CODE"
);

ALTER TABLE "FIXEDASSET_HISTORY_REL" ADD CONSTRAINT "PK_FIXEDASSET_HISTORY_REL" PRIMARY KEY (
	"FIXEDASSET_CODE"
);

ALTER TABLE "LANGUAGE" ADD CONSTRAINT "PK_LANGUAGE" PRIMARY KEY (
	"LANGUAGE_CODE"
);

ALTER TABLE "PROD_EMP_REL" ADD CONSTRAINT "PK_PROD_EMP_REL" PRIMARY KEY (
	"PRODUCT_CODE",
	"EMPLOYEE_CODE"
);

ALTER TABLE "STDACCOUNT" ADD CONSTRAINT "PK_STDACCOUNT" PRIMARY KEY (
	"STDACCOUNT_CODE"
);

ALTER TABLE "DOCJOURNALTYPE" ADD CONSTRAINT "PK_DOCJOURNALTYPE" PRIMARY KEY (
	"DOCJOURNALTYPE_CODE"
);

ALTER TABLE "DOCSALESJOURNAL" ADD CONSTRAINT "PK_DOCSALESJOURNAL" PRIMARY KEY (
	"DOCSALESJOURNAL_CODE",
	"DOCTYPE_CODE"
);

ALTER TABLE "DOCSALESTYPE" ADD CONSTRAINT "PK_DOCSALESTYPE" PRIMARY KEY (
	"DOCSALESTYPE_CODE"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
	"PROJECT_CODE"
);

ALTER TABLE "VATNONDEDUCTIBLE" ADD CONSTRAINT "PK_VATNONDEDUCTIBLE" PRIMARY KEY (
	"VATNONDEDUCTIBLE_CODE"
);

ALTER TABLE "CLOSINGLIST" ADD CONSTRAINT "PK_CLOSINGLIST" PRIMARY KEY (
	"CLOSINGLIST_CODE"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_CODE"
);

ALTER TABLE "PROJ_EMP_REL" ADD CONSTRAINT "PK_PROJ_EMP_REL" PRIMARY KEY (
	"PROJECT_CODE",
	"EMPLOYEE_CODE"
);

ALTER TABLE "CLOSINGACCOUNTLIST" ADD CONSTRAINT "PK_CLOSINGACCOUNTLIST" PRIMARY KEY (
	"ACCOUNT_CODE",
	"CLOSINGLIST_CODE"
);

ALTER TABLE "ABSTRACT" ADD CONSTRAINT "PK_ABSTRACT" PRIMARY KEY (
	"ABSTRACT_ID"
);

ALTER TABLE "TAXREFUNDBANK" ADD CONSTRAINT "PK_TAXREFUNDBANK" PRIMARY KEY (
	"TAXREFUNDBANK_CODE"
);

ALTER TABLE "PRESOA" ADD CONSTRAINT "PK_PRESOA" PRIMARY KEY (
	"PRESOA_SUBJECT"
);

ALTER TABLE "CLIENTCARRYOVER" ADD CONSTRAINT "PK_CLIENTCARRYOVER" PRIMARY KEY (
	"KCLIENTCARRYOVER_CODE",
	"ACCOUNT_CODE"
);

ALTER TABLE "CARDTX" ADD CONSTRAINT "PK_CARDTX" PRIMARY KEY (
	"APPROVE_NUM"
);

ALTER TABLE "CARDINFO" ADD CONSTRAINT "PK_CARDINFO" PRIMARY KEY (
	"CARD_NUM"
);

ALTER TABLE "EXPENDITURE" ADD CONSTRAINT "PK_EXPENDITURE" PRIMARY KEY (
	"EXPENDITURE_NUM"
);

ALTER TABLE "EXPENDITURE_ACCOUNT" ADD CONSTRAINT "PK_EXPENDITURE_ACCOUNT" PRIMARY KEY (
	"ACCOUNT_CODE"
);

ALTER TABLE "VOUCHER" ADD CONSTRAINT "PK_VOUCHER" PRIMARY KEY (
	"VOUCHER_CODE"
);

ALTER TABLE "FIXEDASSET_ISCAR" ADD CONSTRAINT "PK_FIXEDASSET_ISCAR" PRIMARY KEY (
	"FIXEDASSET_ISCAR_CODE"
);

ALTER TABLE "FIXEDASSET_ISSPECIAL" ADD CONSTRAINT "PK_FIXEDASSET_ISSPECIAL" PRIMARY KEY (
	"FIXEDASSET_ISSPECIAL_CODE"
);

ALTER TABLE "FIXEDASSET_TYPE" ADD CONSTRAINT "PK_FIXEDASSET_TYPE" PRIMARY KEY (
	"FIXEDASSET_TYPE_CODE"
);

ALTER TABLE "FIXEDASSET_CUTTYPE" ADD CONSTRAINT "PK_FIXEDASSET_CUTTYPE" PRIMARY KEY (
	"FIXEDASSET_CUTTYPE_CODE"
);

ALTER TABLE "FIXEDASSET_TYPERANGE" ADD CONSTRAINT "PK_FIXEDASSET_TYPERANGE" PRIMARY KEY (
	"FIXEDASSET_TYPERANGE_CODE"
);

ALTER TABLE "ACCOUNTTYPE" ADD CONSTRAINT "PK_ACCOUNTTYPE" PRIMARY KEY (
	"ACCOUNT_TYPE"
);

ALTER TABLE "CLOSINGPREEXP" ADD CONSTRAINT "PK_CLOSINGPREEXP" PRIMARY KEY (
	"DOC_ROWSEQ"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "PK_TRANSACTION" PRIMARY KEY (
	"CODE",
	"MODULE"
);

ALTER TABLE "DOCPRODUCT" ADD CONSTRAINT "FK_DOC_TO_DOCPRODUCT_1" FOREIGN KEY (
	"DOC_ROWSEQ"
)
REFERENCES "DOC" (
	"DOC_ROWSEQ"
);

ALTER TABLE "DOCSALES" ADD CONSTRAINT "FK_DOC_TO_DOCSALES_1" FOREIGN KEY (
	"DOC_ROWSEQ"
)
REFERENCES "DOC" (
	"DOC_ROWSEQ"
);

ALTER TABLE "ACC_AMITEM_REL" ADD CONSTRAINT "FK_ACCOUNT_TO_ACC_AMITEM_REL_1" FOREIGN KEY (
	"ACCOUNT_CODE"
)
REFERENCES "ACCOUNT" (
	"ACCOUNT_CODE"
);

ALTER TABLE "ACC_AMITEM_REL" ADD CONSTRAINT "FK_ADMINITEM_TO_ACC_AMITEM_REL_1" FOREIGN KEY (
	"ADMINITEM_CODE"
)
REFERENCES "ADMINITEM" (
	"ADMINITEM_CODE"
);

ALTER TABLE "FIXEDASSET_HISTORY_REL" ADD CONSTRAINT "FK_FIXEDASSET_TO_FIXEDASSET_HISTORY_REL_1" FOREIGN KEY (
	"FIXEDASSET_CODE"
)
REFERENCES "FIXEDASSET" (
	"FIXEDASSET_CODE"
);

ALTER TABLE "PROD_EMP_REL" ADD CONSTRAINT "FK_PRODUCT_TO_PROD_EMP_REL_1" FOREIGN KEY (
	"PRODUCT_CODE"
)
REFERENCES "PRODUCT" (
	"PRODUCT_CODE"
);

ALTER TABLE "PROD_EMP_REL" ADD CONSTRAINT "FK_EMPLOYEE_TO_PROD_EMP_REL_1" FOREIGN KEY (
	"EMPLOYEE_CODE"
)
REFERENCES "EMPLOYEE" (
	"EMPLOYEE_CODE"
);

ALTER TABLE "DOCSALESJOURNAL" ADD CONSTRAINT "FK_DOCTYPE_TO_DOCSALESJOURNAL_1" FOREIGN KEY (
	"DOCTYPE_CODE"
)
REFERENCES "DOCTYPE" (
	"DOCTYPE_CODE"
);

ALTER TABLE "PROJ_EMP_REL" ADD CONSTRAINT "FK_PROJECT_TO_PROJ_EMP_REL_1" FOREIGN KEY (
	"PROJECT_CODE"
)
REFERENCES "PROJECT" (
	"PROJECT_CODE"
);

ALTER TABLE "PROJ_EMP_REL" ADD CONSTRAINT "FK_EMPLOYEE_TO_PROJ_EMP_REL_1" FOREIGN KEY (
	"EMPLOYEE_CODE"
)
REFERENCES "EMPLOYEE" (
	"EMPLOYEE_CODE"
);

ALTER TABLE "CLOSINGACCOUNTLIST" ADD CONSTRAINT "FK_ACCOUNT_TO_CLOSINGACCOUNTLIST_1" FOREIGN KEY (
	"ACCOUNT_CODE"
)
REFERENCES "ACCOUNT" (
	"ACCOUNT_CODE"
);

ALTER TABLE "CLOSINGACCOUNTLIST" ADD CONSTRAINT "FK_CLOSINGLIST_TO_CLOSINGACCOUNTLIST_1" FOREIGN KEY (
	"CLOSINGLIST_CODE"
)
REFERENCES "CLOSINGLIST" (
	"CLOSINGLIST_CODE"
);

ALTER TABLE "CLIENTCARRYOVER" ADD CONSTRAINT "FK_ACCOUNT_TO_CLIENTCARRYOVER_1" FOREIGN KEY (
	"ACCOUNT_CODE"
)
REFERENCES "ACCOUNT" (
	"ACCOUNT_CODE"
);

ALTER TABLE "CLOSINGPREEXP" ADD CONSTRAINT "FK_DOC_TO_CLOSINGPREEXP_1" FOREIGN KEY (
	"DOC_ROWSEQ"
)
REFERENCES "DOC" (
	"DOC_ROWSEQ"
);

